# Generated by Django 2.2.24 on 2022-01-08 14:22

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Neighbourhood_app', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('business_photo', models.ImageField(upload_to='images/')),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='Neighbourhood_app.NeighbourHood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='Neighbourhood_app.Profile')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
